### ISSUE TITLE
CSS - homework2

### ISSUE THREAD

**Issue by chnbohwr** [bonnieyu53/training_schedule#2]
![image](https://user-images.githubusercontent.com/6761222/36823656-24ebae6a-1d39-11e8-8f56-408d2289f3f2.png)
![image](https://user-images.githubusercontent.com/6761222/36823690-51e66c3e-1d39-11e8-8346-011693e25466.png)

請嘗試使用漸層背景完成

![image](https://user-images.githubusercontent.com/6761222/36823678-40a5ac0a-1d39-11e8-8a81-437716056b71.png)
請嘗試使用漸層文字完成

```scss
@mixin displayFlex {
    display: flex;
    display: -webkit-flex;
}
```
我有在 scss 裡面發現你為了要讓chrome瀏覽器支援flex添加了 `-webkit-` ，可以找看看有哪些工具可以自動幫你添加（這是建議不一定要做）
